---
- name: "Install Golang"
  
  
  vars:  
      go_version: "1.20.5"
  
  get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "/tmp/go.tar.gz"
    mode: '0644'
    

- name: Extract Go tarball
  become: true
  unarchive:
    src: "/tmp/go.tar.gz"
    dest: "/usr/local"
    remote_src: yes
    creates: "/usr/local/go"

- name: Add Go bin directory to User PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "export PATH=$PATH:/usr/local/go/bin"
    state: present
  #become_user: "{{ansible_user}}"
  #become_method: su

- name: Cleaning up
  become: true
  shell: |
    rm -rf /usr/lib/go
    rm -rf /tmp/go.tar.gz